export interface CountryCode {
  label: string;
  value: string;
  dialCode: string;
}

export const DEFAULT_DIAL_CODE = "+977";

export const COUNTRY_CODES: CountryCode[] = [
  { label: "Nepal", value: "nepal", dialCode: "+977" },
  { label: "India", value: "india", dialCode: "+91" },
  { label: "Bangladesh", value: "bangladesh", dialCode: "+880" },
  { label: "Bhutan", value: "bhutan", dialCode: "+975" },
  { label: "Sri Lanka", value: "sri_lanka", dialCode: "+94" },
  { label: "Pakistan", value: "pakistan", dialCode: "+92" },
  { label: "Afghanistan", value: "afghanistan", dialCode: "+93" },
  { label: "Albania", value: "albania", dialCode: "+355" },
  { label: "Algeria", value: "algeria", dialCode: "+213" },
  { label: "Andorra", value: "andorra", dialCode: "+376" },
  { label: "Angola", value: "angola", dialCode: "+244" },
  { label: "Antigua & Barbuda", value: "antigua_barbuda", dialCode: "+1" },
  { label: "Argentina", value: "argentina", dialCode: "+54" },
  { label: "Armenia", value: "armenia", dialCode: "+374" },
  { label: "Australia", value: "australia", dialCode: "+61" },
  { label: "Austria", value: "austria", dialCode: "+43" },
  { label: "Azerbaijan", value: "azerbaijan", dialCode: "+994" },
  { label: "Bahamas", value: "bahamas", dialCode: "+1" },
  { label: "Bahrain", value: "bahrain", dialCode: "+973" },
  { label: "Barbados", value: "barbados", dialCode: "+1" },
  { label: "Belarus", value: "belarus", dialCode: "+375" },
  { label: "Belgium", value: "belgium", dialCode: "+32" },
  { label: "Belize", value: "belize", dialCode: "+501" },
  { label: "Benin", value: "benin", dialCode: "+229" },
  { label: "Bolivia", value: "bolivia", dialCode: "+591" },
  { label: "Bosnia", value: "bosnia", dialCode: "+387" },
  { label: "Botswana", value: "botswana", dialCode: "+267" },
  { label: "Brazil", value: "brazil", dialCode: "+55" },
  { label: "Brunei", value: "brunei", dialCode: "+673" },
  { label: "Bulgaria", value: "bulgaria", dialCode: "+359" },
  { label: "Burkina Faso", value: "burkina_faso", dialCode: "+226" },
  { label: "Burundi", value: "burundi", dialCode: "+257" },
  { label: "Cambodia", value: "cambodia", dialCode: "+855" },
  { label: "Cameroon", value: "cameroon", dialCode: "+237" },
  { label: "Canada", value: "canada", dialCode: "+1" },
  { label: "Cape Verde", value: "cape_verde", dialCode: "+238" },
  { label: "Central African Republic", value: "central_african_republic", dialCode: "+236" },
  { label: "Chad", value: "chad", dialCode: "+235" },
  { label: "Chile", value: "chile", dialCode: "+56" },
  { label: "China", value: "china", dialCode: "+86" },
  { label: "Colombia", value: "colombia", dialCode: "+57" },
  { label: "Comoros", value: "comoros", dialCode: "+269" },
  { label: "Congo", value: "congo", dialCode: "+242" },
  { label: "Costa Rica", value: "costa_rica", dialCode: "+506" },
  { label: "Croatia", value: "croatia", dialCode: "+385" },
  { label: "Cuba", value: "cuba", dialCode: "+53" },
  { label: "Cyprus", value: "cyprus", dialCode: "+357" },
  { label: "Czech Republic", value: "czech_republic", dialCode: "+420" },
  { label: "DR Congo", value: "dr_congo", dialCode: "+243" },
  { label: "Denmark", value: "denmark", dialCode: "+45" },
  { label: "Djibouti", value: "djibouti", dialCode: "+253" },
  { label: "Dominica", value: "dominica", dialCode: "+1" },
  { label: "Dominican Republic", value: "dominican_republic", dialCode: "+1" },
  { label: "Ecuador", value: "ecuador", dialCode: "+593" },
  { label: "Egypt", value: "egypt", dialCode: "+20" },
  { label: "El Salvador", value: "el_salvador", dialCode: "+503" },
  { label: "Equatorial Guinea", value: "equatorial_guinea", dialCode: "+240" },
  { label: "Eritrea", value: "eritrea", dialCode: "+291" },
  { label: "Estonia", value: "estonia", dialCode: "+372" },
  { label: "Eswatini", value: "eswatini", dialCode: "+268" },
  { label: "Ethiopia", value: "ethiopia", dialCode: "+251" },
  { label: "Fiji", value: "fiji", dialCode: "+679" },
  { label: "Finland", value: "finland", dialCode: "+358" },
  { label: "France", value: "france", dialCode: "+33" },
  { label: "Gabon", value: "gabon", dialCode: "+241" },
  { label: "Gambia", value: "gambia", dialCode: "+220" },
  { label: "Georgia", value: "georgia", dialCode: "+995" },
  { label: "Germany", value: "germany", dialCode: "+49" },
  { label: "Ghana", value: "ghana", dialCode: "+233" },
  { label: "Greece", value: "greece", dialCode: "+30" },
  { label: "Grenada", value: "grenada", dialCode: "+1" },
  { label: "Guatemala", value: "guatemala", dialCode: "+502" },
  { label: "Guinea", value: "guinea", dialCode: "+224" },
  { label: "Guinea-Bissau", value: "guinea_bissau", dialCode: "+245" },
  { label: "Guyana", value: "guyana", dialCode: "+592" },
  { label: "Haiti", value: "haiti", dialCode: "+509" },
  { label: "Honduras", value: "honduras", dialCode: "+504" },
  { label: "Hong Kong", value: "hong_kong", dialCode: "+852" },
  { label: "Hungary", value: "hungary", dialCode: "+36" },
  { label: "Iceland", value: "iceland", dialCode: "+354" },
  { label: "Indonesia", value: "indonesia", dialCode: "+62" },
  { label: "Iran", value: "iran", dialCode: "+98" },
  { label: "Iraq", value: "iraq", dialCode: "+964" },
  { label: "Ireland", value: "ireland", dialCode: "+353" },
  { label: "Israel", value: "israel", dialCode: "+972" },
  { label: "Italy", value: "italy", dialCode: "+39" },
  { label: "Ivory Coast", value: "ivory_coast", dialCode: "+225" },
  { label: "Jamaica", value: "jamaica", dialCode: "+1" },
  { label: "Japan", value: "japan", dialCode: "+81" },
  { label: "Jordan", value: "jordan", dialCode: "+962" },
  { label: "Kazakhstan", value: "kazakhstan", dialCode: "+7" },
  { label: "Kenya", value: "kenya", dialCode: "+254" },
  { label: "Kiribati", value: "kiribati", dialCode: "+686" },
  { label: "Kosovo", value: "kosovo", dialCode: "+383" },
  { label: "Kuwait", value: "kuwait", dialCode: "+965" },
  { label: "Kyrgyzstan", value: "kyrgyzstan", dialCode: "+996" },
  { label: "Laos", value: "laos", dialCode: "+856" },
  { label: "Latvia", value: "latvia", dialCode: "+371" },
  { label: "Lebanon", value: "lebanon", dialCode: "+961" },
  { label: "Lesotho", value: "lesotho", dialCode: "+266" },
  { label: "Liberia", value: "liberia", dialCode: "+231" },
  { label: "Libya", value: "libya", dialCode: "+218" },
  { label: "Liechtenstein", value: "liechtenstein", dialCode: "+423" },
  { label: "Lithuania", value: "lithuania", dialCode: "+370" },
  { label: "Luxembourg", value: "luxembourg", dialCode: "+352" },
  { label: "Macau", value: "macau", dialCode: "+853" },
  { label: "Madagascar", value: "madagascar", dialCode: "+261" },
  { label: "Malawi", value: "malawi", dialCode: "+265" },
  { label: "Malaysia", value: "malaysia", dialCode: "+60" },
  { label: "Maldives", value: "maldives", dialCode: "+960" },
  { label: "Mali", value: "mali", dialCode: "+223" },
  { label: "Malta", value: "malta", dialCode: "+356" },
  { label: "Marshall Islands", value: "marshall_islands", dialCode: "+692" },
  { label: "Mauritania", value: "mauritania", dialCode: "+222" },
  { label: "Mauritius", value: "mauritius", dialCode: "+230" },
  { label: "Mexico", value: "mexico", dialCode: "+52" },
  { label: "Micronesia", value: "micronesia", dialCode: "+691" },
  { label: "Moldova", value: "moldova", dialCode: "+373" },
  { label: "Monaco", value: "monaco", dialCode: "+377" },
  { label: "Mongolia", value: "mongolia", dialCode: "+976" },
  { label: "Montenegro", value: "montenegro", dialCode: "+382" },
  { label: "Morocco", value: "morocco", dialCode: "+212" },
  { label: "Mozambique", value: "mozambique", dialCode: "+258" },
  { label: "Myanmar", value: "myanmar", dialCode: "+95" },
  { label: "Namibia", value: "namibia", dialCode: "+264" },
  { label: "Nauru", value: "nauru", dialCode: "+674" },
  { label: "Netherlands", value: "netherlands", dialCode: "+31" },
  { label: "New Zealand", value: "new_zealand", dialCode: "+64" },
  { label: "Nicaragua", value: "nicaragua", dialCode: "+505" },
  { label: "Niger", value: "niger", dialCode: "+227" },
  { label: "Nigeria", value: "nigeria", dialCode: "+234" },
  { label: "North Korea", value: "north_korea", dialCode: "+850" },
  { label: "North Macedonia", value: "north_macedonia", dialCode: "+389" },
  { label: "Norway", value: "norway", dialCode: "+47" },
  { label: "Oman", value: "oman", dialCode: "+968" },
  { label: "Palau", value: "palau", dialCode: "+680" },
  { label: "Palestine", value: "palestine", dialCode: "+970" },
  { label: "Panama", value: "panama", dialCode: "+507" },
  { label: "Papua New Guinea", value: "papua_new_guinea", dialCode: "+675" },
  { label: "Paraguay", value: "paraguay", dialCode: "+595" },
  { label: "Peru", value: "peru", dialCode: "+51" },
  { label: "Philippines", value: "philippines", dialCode: "+63" },
  { label: "Poland", value: "poland", dialCode: "+48" },
  { label: "Portugal", value: "portugal", dialCode: "+351" },
  { label: "Qatar", value: "qatar", dialCode: "+974" },
  { label: "Romania", value: "romania", dialCode: "+40" },
  { label: "Russia", value: "russia", dialCode: "+7" },
  { label: "Rwanda", value: "rwanda", dialCode: "+250" },
  { label: "Saint Kitts & Nevis", value: "saint_kitts_nevis", dialCode: "+1" },
  { label: "Saint Lucia", value: "saint_lucia", dialCode: "+1" },
  { label: "Saint Vincent & the Grenadines", value: "saint_vincent_grenadines", dialCode: "+1" },
  { label: "Samoa", value: "samoa", dialCode: "+685" },
  { label: "San Marino", value: "san_marino", dialCode: "+378" },
  { label: "Sao Tome & Principe", value: "sao_tome_principe", dialCode: "+239" },
  { label: "Saudi Arabia", value: "saudi_arabia", dialCode: "+966" },
  { label: "Senegal", value: "senegal", dialCode: "+221" },
  { label: "Serbia", value: "serbia", dialCode: "+381" },
  { label: "Seychelles", value: "seychelles", dialCode: "+248" },
  { label: "Sierra Leone", value: "sierra_leone", dialCode: "+232" },
  { label: "Singapore", value: "singapore", dialCode: "+65" },
  { label: "Slovakia", value: "slovakia", dialCode: "+421" },
  { label: "Slovenia", value: "slovenia", dialCode: "+386" },
  { label: "Solomon Islands", value: "solomon_islands", dialCode: "+677" },
  { label: "Somalia", value: "somalia", dialCode: "+252" },
  { label: "South Africa", value: "south_africa", dialCode: "+27" },
  { label: "South Korea", value: "south_korea", dialCode: "+82" },
  { label: "South Sudan", value: "south_sudan", dialCode: "+211" },
  { label: "Spain", value: "spain", dialCode: "+34" },
  { label: "Sudan", value: "sudan", dialCode: "+249" },
  { label: "Suriname", value: "suriname", dialCode: "+597" },
  { label: "Sweden", value: "sweden", dialCode: "+46" },
  { label: "Switzerland", value: "switzerland", dialCode: "+41" },
  { label: "Syria", value: "syria", dialCode: "+963" },
  { label: "Taiwan", value: "taiwan", dialCode: "+886" },
  { label: "Tajikistan", value: "tajikistan", dialCode: "+992" },
  { label: "Tanzania", value: "tanzania", dialCode: "+255" },
  { label: "Thailand", value: "thailand", dialCode: "+66" },
  { label: "Timor-Leste", value: "timor_leste", dialCode: "+670" },
  { label: "Togo", value: "togo", dialCode: "+228" },
  { label: "Tonga", value: "tonga", dialCode: "+676" },
  { label: "Trinidad & Tobago", value: "trinidad_tobago", dialCode: "+1" },
  { label: "Tunisia", value: "tunisia", dialCode: "+216" },
  { label: "Turkey", value: "turkey", dialCode: "+90" },
  { label: "Turkmenistan", value: "turkmenistan", dialCode: "+993" },
  { label: "UAE", value: "uae", dialCode: "+971" },
  { label: "Uganda", value: "uganda", dialCode: "+256" },
  { label: "Ukraine", value: "ukraine", dialCode: "+380" },
  { label: "United Kingdom", value: "uk", dialCode: "+44" },
  { label: "United States", value: "usa", dialCode: "+1" },
  { label: "Uruguay", value: "uruguay", dialCode: "+598" },
  { label: "Uzbekistan", value: "uzbekistan", dialCode: "+998" },
  { label: "Vanuatu", value: "vanuatu", dialCode: "+678" },
  { label: "Vatican City", value: "vatican_city", dialCode: "+379" },
  { label: "Venezuela", value: "venezuela", dialCode: "+58" },
  { label: "Vietnam", value: "vietnam", dialCode: "+84" },
  { label: "Yemen", value: "yemen", dialCode: "+967" },
  { label: "Zambia", value: "zambia", dialCode: "+260" },
  { label: "Zimbabwe", value: "zimbabwe", dialCode: "+263" },
];
